#!/bin/bash

readonly input_file=$(mktemp /tmp/input.XXXXXX)

if [ "$#" = 5 ]; then
    echo "{
        \"source\": {
            \"download_key\": \"${1}\",
            \"group\": \"${2}\",
            \"artifact\": \"${3}\",
            \"file_name\": \"${4}\",
            \"check_etag\": true,
            \"skip_ssl_verification\": true
        },
        \"version\": {
            \"version\": \"${5}\"
        }
    }" > "${input_file}"
elif [ "$#" = 4 ]; then
    echo "{
        \"source\": {
            \"download_key\": \"${1}\",
            \"group\": \"${2}\",
            \"artifact\": \"${3}\",
            \"file_name\": \"${4}\",
            \"check_etag\": true,
            \"skip_ssl_verification\": true
        }
    }" > "${input_file}"
else
    echo "Wrong number of arguments, you have provided $# arguments, this script needs either 4 or 5 arguments."
    echo "Usage: $0 download_key group artifact file_name [version]"
    exit 1
fi

docker run -i instana/artifactory-resource:latest bash -x /opt/resource/check < "${input_file}"
