#!/bin/bash

readonly input_file=$(mktemp /tmp/input.XXXXXX)

if [ -n "${5}" ]; then
    echo "{
        \"source\": {
            \"download_key\": \"${1}\",
            \"group\": \"${2}\",
            \"artifact\": \"${3}\",
            \"file_name\": \"${4}\",
            \"check_etag\": false,
            \"skip_ssl_verification\": true
        },
        \"version\": {
            \"version\": \"${5}\"
        }
    }" > "${input_file}"
else
    echo "{
        \"source\": {
            \"download_key\": \"${1}\",
            \"group\": \"${2}\",
            \"artifact\": \"${3}\",
            \"file_name\": \"${4}\",
            \"check_etag\": false,
            \"skip_ssl_verification\": true
        }
    }" > "${input_file}"
fi

docker run -i instana/artifactory-resource:latest bash -x /opt/resource/in . < "${input_file}"